import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "@playwright/test";
import dotenv from "dotenv";

// Convert import.meta.url to __filename and __dirname
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const playwrightReportDir = "./tests/report/playwright-report";
const smartReportFile = `${playwrightReportDir}/smart-report.html`;
const smartHistoryFile = "./tests/report/smart-reporter-history/test-history.json";

// Load environment variables
dotenv.config({ path: path.resolve(__dirname, ".env") });

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
	/* Fail the build on CI if you accidentally left test.only in the source code. */
	forbidOnly: !!process.env.CI,
	/* Retry on CI only */
	retries: process.env.CI ? 2 : 0,
	/* Reporter to use. See https://playwright.dev/docs/test-reporters */
	reporter: [
		["html", { outputFolder: playwrightReportDir }],
		[
			"playwright-smart-reporter",
			{
				outputFile: smartReportFile,
				historyFile: smartHistoryFile,
				maxHistoryRuns: 30,
				runId: process.env.GITHUB_RUN_ID,
				branding: {
					title: "Playwright UI & API Report",
					footer: "Generated by playwright-smart-reporter",
				},
			},
		],
		["list"],
	],

	/* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
	use: {
		trace: "retain-on-failure",
		baseURL: "https://conduit.bondaracademy.com",
	},

	/* Configure projects for major browsers */
	projects: [
		{
			name: "ui-tests",
			use: {
				screenshot: "only-on-failure",
				defaultBrowserType: "chromium",
			},
			testDir: "./tests/ui-tests",
			outputDir: "./tests/report/test-results/ui-tests",
			fullyParallel: true,
			workers: process.env.CI ? 2 : undefined,
		},
		/**
		 * uncomment below if you want to have an PW-API project
		 */
		{
			name: "api-tests",
			testDir: "./tests/api-tests",
			workers: 1,
			outputDir: "./tests/report/test-results/api-tests",
		},
	],
});
